// -*- C++ -*-
//
// generated by wxGlade 0.9.4 on Wed Apr 27 00:19:21 2022
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef WXGLADE_OUT_H
#define WXGLADE_OUT_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
#include <robotmonitor.hpp>

#include "magnetometer.h"
#include "orientation.h"
// end wxGlade


class MyFrame: public wxFrame {
private:
    rmClient client;
    rmTimer timer;
    Section *sections[4];
    int sectionCount = 0;
    bool initDone = false;
    
    void userConstruct();
    
public:
    void onPortDetected(wxEvent& evt);
    void onResize(wxSizeEvent& evt);
    void onBtnConnect_enter(wxMouseEvent& evt);
    void onBtnConnect_leave(wxMouseEvent& evt);
    void onBtnConnect_press(wxMouseEvent& evt);
    void onBtnConnect_release(wxMouseEvent& evt);
    
public:
    // begin wxGlade: MyFrame::ids
    // end wxGlade

    MyFrame(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: MyFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MyFrame::attributes
    wxChoice* chMenu;
    wxChoice* chPort;
    wxButton* btnConnect;
    wxPanel* pnlToolBar;
    wxBoxSizer* sizerFocus;
    wxTextCtrl* txtEcho;
    wxStaticBoxSizer* sizerEcho;
    wxBoxSizer* sizerWidgets;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void onMenuSelection(wxCommandEvent &event); // wxGlade: <event_handler>
    void onBtnConnect(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // WXGLADE_OUT_H
