// -*- C++ -*-
//
// generated by wxGlade 0.9.4 on Sun Apr  4 19:28:41 2021
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef WXGLADE_OUT_H
#define WXGLADE_OUT_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
#include <wx/tglbtn.h>
// end wxGlade

// begin wxGlade: ::extracode
#include <rm/button.hpp>
#include <rm/slider.hpp>
#include <rm/spinctrl.hpp>
#include <rm/textctrl.hpp>
#include <rm/checkbox.hpp>
#include <rm/gauge.hpp>
#include <rm/stattext.hpp>
// end wxGlade


class MyFrame: public wxFrame {
public:
    // begin wxGlade: MyFrame::ids
    // end wxGlade

    MyFrame(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: MyFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade
    rmClient client;

protected:
    // begin wxGlade: MyFrame::attributes
    rmGauge* gauge_1;
    wxChoice* choice_1;
    rmCheckBox* checkbox_2;
    rmCheckBox* checkbox_3;
    rmCheckBox* checkbox_1;
    rmTextCtrl* text_ctrl_1;
    rmSpinCtrl* spin_ctrl_1;
    rmSlider* slider_1;
    wxToggleButton* button_1;
    rmButton* button_2;
    wxRadioBox* radio_box_1;
    // end wxGlade
}; // wxGlade: end class


#endif // WXGLADE_OUT_H
